# dbdevu14 is a koadstation Ubuntu 14 database development environment
# installs
# - PostgreSQL 9.5
# - MySQL 5.7
# - Redis

require 'rbconfig'

is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)

PRIVATE_IP = '10.0.4.30'
FORWARDED_SSH =   3322

Vagrant.configure('2') do |config|

  # set ssh shell to sh to be able to run step 000
  # to get bash in there to run further bash based provisioning scripts
  config.ssh.shell = 'sh'

  # servers available for provisioning
  # before doing default bootstrap env to jump into boxes with ansible
  config.vm.define 'default' do |dbdev|
    dbdev.vm.box = 'ubuntu/trusty64'

    dbdev.vm.network 'private_network', ip: PRIVATE_IP

    dbdev.vm.network 'forwarded_port', guest: 22, host: FORWARDED_SSH, id: 'ssh'

    # set dir and file modes to minimize ansible inventory file confusion
    dbdev.vm.synced_folder '.', '/vagrant', :mount_options => ["dmode=777","fmode=666"]

    dbdev.vm.provider 'virtualbox' do |vb|
      # vb.gui = true
      vb.memory = 4096
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    # if ansible ppa failed to install
    # remove ansible 1.5 that ships with the trusty box
    # if ansible ppa is installed then this will cause step 010 to upgrade
    # all ppa, repos, and packages and result in installing the required ansible 1.9+
    # this should only be done if initial provisioning failed to install the ansible ppa
    #dbdev.vm.provision 'shell', inline: 'apt-get -q -y remove ansible', privileged: true

    # provision step 010 - bootstrap ansible
    dbdev.vm.provision 'shell', path: 'provisioning/step-010_bootstrap.sh', args: [PRIVATE_IP], privileged: true

    # provision step 100 - postgresql
    dbdev.vm.provision 'shell', path: 'provisioning/step-100_postgresql.sh', privileged: true

    # provision step 101 - mysql
    dbdev.vm.provision 'shell', path: 'provisioning/step-101_mysql.sh', privileged: true

    # provision step 102 - redis
    dbdev.vm.provision 'shell', path: 'provisioning/step-102_redis.sh', privileged: true
  end

end
