# dbdevf3 is a koadstation FreeBSD 10.3 database development environment
# installs
# - PostgreSQL 9.5
# - MySQL 5.7
# - Redis

require 'rbconfig'

is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)

PRIVATE_IP = '10.0.4.30'
FORWARDED_SSH =   4322

Vagrant.configure('2') do |config|

  # set ssh shell to sh to be able to run step 000
  # to get bash in there to run further bash based provisioning scripts
  config.ssh.shell = 'sh'

  # servers available for provisioning
  # before doing default bootstrap env to jump into boxes with ansible
  config.vm.define 'default' do |freebsddb|
    freebsddb.vm.box = 'freebsd/FreeBSD-10.3-RELEASE'
    freebsddb.vm.guest = :freebsd

    freebsddb.vm.network 'private_network', ip: PRIVATE_IP

    freebsddb.vm.network 'forwarded_port', guest: 22, host: FORWARDED_SSH, id: 'ssh'

    # disable default share for now, need to work on windows to freebsd virtualbox sharing
    freebsddb.vm.synced_folder '.', '/vagrant', disabled: true

    freebsddb.vm.provider 'virtualbox' do |vb|
      # vb.gui = true
      vb.memory = 1024
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end
  
    # provision step 000 - get bash in VM for more complex provisioning
    # above in configure() we set config.ssh.shell to sh so the shebang being used is sh instead of bash
    freebsddb.vm.provision 'shell', inline: 'pkg install --yes shells/bash', privileged: true

    # provision step 010 - bootstrap ansible
    freebsddb.vm.provision 'shell', path: 'provisioning/step-010_bootstrap.sh', args: [PRIVATE_IP], privileged: true

    # provision step 020 - tools
    freebsddb.vm.provision 'shell', path: 'provisioning/step-020_tools.sh', privileged: true

    # provision step 100 - postgresql
    freebsddb.vm.provision 'shell', path: 'provisioning/step-100_postgresql.sh', privileged: true

    # provision step 101 - mysql
    freebsddb.vm.provision 'shell', path: 'provisioning/step-101_mysql.sh', privileged: true

    # provision step 102 - redis
    freebsddb.vm.provision 'shell', path: 'provisioning/step-102_redis.sh', privileged: true
  end

end
