require 'rbconfig'

is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)

TILESERVER_IP = '10.0.3.10'
TILESERVER_SSH   = 3022
TILESERVER_HTTP  = 3080
TILESERVER_HTTPS = 3443

Vagrant.configure('2') do |config|

  config.vm.define 'default' do |maptile|
    maptile.vm.box = 'ubuntu/trusty64'

    maptile.vm.network 'private_network', ip: TILESERVER_IP

    maptile.vm.network 'forwarded_port', guest: 22, host: TILESERVER_SSH, id: 'ssh'

    # set dir and file modes to minimize ansible inventory file confusion
    maptile.vm.synced_folder '.', '/vagrant', :mount_options => ["dmode=777","fmode=666"]

    maptile.vm.provider 'virtualbox' do |vb|
      # vb.gui = true
      # need atleast 8GB RAM for map imports - more depending on size of pbf
      vb.memory = 8096
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    # if ansible ppa failed to install
    # remove ansible 1.5 that ships with the trusty box
    # if ansible ppa is installed then this will cause step 010 to upgrade
    # all ppa, repos, and packages and result in installing the required ansible 1.9+
    # this should only be done if initial provisioning failed to install the ansible ppa
    #maptile.vm.provision 'shell', inline: 'apt-get -q -y remove ansible', privileged: true

    # provision step 010 - update apt-get and ansible
    maptile.vm.provision 'shell', path: 'provisioning/step-010_apt-get-ansible.sh', args: [TILESERVER_IP], privileged: false

    # provision step 020 - install server components
    maptile.vm.provision 'shell', path: 'provisioning/step-020_server-components.sh', args: [TILESERVER_IP], privileged: false

    # provision step 030 - build map tile database
    maptile.vm.provision 'shell', path: 'provisioning/step-030_build-database.sh', args: [TILESERVER_IP, TILESERVER_HTTPS.to_s], privileged: false

    # provision step 040 - install import tools
    maptile.vm.provision 'shell', path: 'provisioning/step-040_import-tools.sh', args: [TILESERVER_IP], privileged: false
  end

end
