require 'rbconfig'

is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)

JAILHOST_IP     = '10.0.5.10'
JAILHOST_SSH    = 5022
BOOTSTRAP_IP    = '10.0.5.11'
BOOTSTRAP_SSH   = 5122
# functional jail IPs can be found in the provisioning/jails.yml

Vagrant.configure('2') do |config|

  # servers available for provisioning
  # before doing default bootstrap env to jump into boxes with ansible
  config.vm.define 'jailhost' do |jailhost|
    jailhost.vm.box = 'arkadi/freebsd-10.1-amd64'
    jailhost.vm.guest = :freebsd

    # the jails made in this VM are bound to loopback lo1 and em0 NAT interface
    # see provisioning/jails.yml
    jailhost.vm.network 'private_network', ip: JAILHOST_IP

    jailhost.vm.network 'forwarded_port', guest: 22, host: JAILHOST_SSH, id: 'ssh'

    # disable default share for now, need to work on windows to freebsd virtualbox sharing
    jailhost.vm.synced_folder '.', '/vagrant', disabled: true

    jailhost.vm.provider 'virtualbox' do |vb|
      # vb.gui = true
      vb.memory = 1024
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    # provision step 010 - update pkg and ansible
    jailhost.vm.provision 'shell', path: 'provisioning/step-010_pkg-ansible.sh', args: [JAILHOST_IP], privileged: true
  end

  config.vm.define 'default' do |bootstrap|
    bootstrap.vm.box = 'chef/centos-6.6'

    bootstrap.vm.network 'private_network', ip: BOOTSTRAP_IP

    bootstrap.vm.network 'forwarded_port', guest: 22, host: BOOTSTRAP_SSH, id: 'ssh'

    # set dir and file modes to minimize ansible confusion
    bootstrap.vm.synced_folder '.', '/vagrant', :mount_options => ["dmode=777","fmode=666"]

    bootstrap.vm.provider 'virtualbox' do |vb|
      # vb.gui = true
      vb.memory = 512
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    # install vagrant host insecure_private_key to use when connecting to jailhost with ansible from bootstrap vm
    bootstrap.vm.provision 'file', source: '~/.vagrant.d/insecure_private_key', destination: '~/vagrant_insecure_private_key'

    # provision step 110 - update bootstrap yum and ansible
    bootstrap.vm.provision 'shell', path: 'provisioning/step-110_yum-ansible.sh', args: [JAILHOST_IP], privileged: true

    # provision step 111 - install bootstrap tools
    bootstrap.vm.provision 'shell', path: 'provisioning/step-111_bootstrap-tools.sh', args: [JAILHOST_IP], privileged: false

    # provision step 210 - setup freebsd jails
    bootstrap.vm.provision 'shell', path: 'provisioning/step-210_jails.sh', args: [JAILHOST_IP], privileged: false
  end

end
