---

- name: webdevj1 Provisioning Step 210 - jail configuration and provisioning
  hosts: all
  gather_facts: no
  sudo: yes

  vars_files:
    - jails.yml

  roles:
    - role: jailhost


- name: provision webserver jails
  hosts: webserverjails
  sudo: yes
  gather_facts: False
  roles: [webserver-apache24]

- name: provision redis jails
  hosts: redisjails
  sudo: yes
  gather_facts: False
  roles: [redis30]
