require 'rbconfig'

is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)

MACHINE_IP = '10.0.4.10'
SSH_PORT = 4022
HTTP_PORT = 4080
HTTPS_PORT = 4443

Vagrant.configure('2') do |config|

  config.vm.define 'default' do |webdevfreebsd|
    webdevfreebsd.vm.box = 'arkadi/freebsd-10.1-amd64'
    webdevfreebsd.vm.guest = :freebsd

    webdevfreebsd.vm.network 'private_network', ip: MACHINE_IP

    webdevfreebsd.vm.network 'forwarded_port', guest: 22, host: SSH_PORT, id: 'ssh'
    webdevfreebsd.vm.network 'forwarded_port', guest: 80, host: HTTP_PORT
    webdevfreebsd.vm.network 'forwarded_port', guest: 443, host: HTTPS_PORT

    # disable default share for now, need to work on windows to freebsd virtualbox sharing
    webdevfreebsd.vm.synced_folder '.', '/vagrant', disabled: true

    webdevfreebsd.vm.provider 'virtualbox' do |vb|
      # vb.gui = true
      vb.memory = 512
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    # provision step 001
    # update and configure pkg
    webdevfreebsd.vm.provision 'shell', path: 'provisioning/provision-001_pkg-ansible.sh', args: [MACHINE_IP], privileged: false

    # provision step 002
    # install jail host administration and configuration packages
    webdevfreebsd.vm.provision 'shell', path: 'provisioning/provision-010_baseline.sh', args: [MACHINE_IP], privileged: false
  end

end
