require 'rbconfig'

is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)

BOOTSTRAP_IP = '10.0.4.10'
WEBSERVER_IP = '10.0.4.50'
WEBSERVER_SSH   = 5022
WEBSERVER_HTTP  = 5080
WEBSERVER_HTTPS = 5443

Vagrant.configure('2') do |config|

  # servers available for provisioning
  # before doing default bootstrap env to jump into boxes with ansible
  config.vm.define 'webserver' do |freebsdweb|
    freebsdweb.vm.box = 'arkadi/freebsd-10.1-amd64'
    freebsdweb.vm.guest = :freebsd

    freebsdweb.vm.network 'private_network', ip: WEBSERVER_IP

    freebsdweb.vm.network 'forwarded_port', guest: 22, host: WEBSERVER_SSH, id: 'ssh'
    freebsdweb.vm.network 'forwarded_port', guest: 80, host: WEBSERVER_HTTP
    freebsdweb.vm.network 'forwarded_port', guest: 443, host: WEBSERVER_HTTPS

    # disable default share for now, need to work on windows to freebsd virtualbox sharing
    freebsdweb.vm.synced_folder '.', '/vagrant', disabled: true

    freebsdweb.vm.provider 'virtualbox' do |vb|
      # vb.gui = true
      vb.memory = 512
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end
  end

  config.vm.define 'default' do |bootstrap|
    bootstrap.vm.box = 'chef/centos-6.6'

    bootstrap.vm.network 'private_network', ip: BOOTSTRAP_IP

    bootstrap.vm.network 'forwarded_port', guest: 22, host: 4022, id: 'ssh'

    # set dir and file modes to minimize ansible confusion
    bootstrap.vm.synced_folder '.', '/vagrant', :mount_options => ["dmode=777","fmode=666"]

    bootstrap.vm.provider 'virtualbox' do |vb|
      # vb.gui = true
      vb.memory = 512
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    # provision step 010 - update yum and ansible
    bootstrap.vm.provision 'shell', path: 'provisioning/step-010_yum-ansible.sh', args: [WEBSERVER_IP], privileged: false

    # provision step 011 - install build tools
    bootstrap.vm.provision 'shell', path: 'provisioning/step-011_build-tools.sh', args: [WEBSERVER_IP], privileged: false

    # provision step 020 - update pkg and ansible
    bootstrap.vm.provision 'shell', path: 'provisioning/step-020_pkg-ansible.sh', args: [WEBSERVER_IP], privileged: false

    # provision step 021 - web server packages and configuration
    bootstrap.vm.provision 'shell', path: 'provisioning/step-021_servers.sh', args: [WEBSERVER_IP, WEBSERVER_HTTPS.to_s], privileged: false
  end

end
